### ISSUE TITLE
SQL Error: 90097 The database is read only; SQL statement:

### ISSUE THREAD

**Issue by crackZ44** [gameyfin/gameyfin#395]
After closing the programm (ctrl+c in terminal) and reopening i cant edit any games
Webpage presents error window without error text 3 times.

SQL Error: 90097
The database is read only; SQL statement:

What am I doing wrong, is there a way to stop the server gracefully?

 - Installation method: bare metal
 - Java JDK 22.0.2
 - Gameyfin version v1.4.6
[log.txt](https://github.com/user-attachments/files/17032693/log.txt)

**Comment by crackZ44** [comment]
![2024-09-17 19_27_15-Gameyfin – Mozilla Firefox](https://github.com/user-attachments/assets/5ae1f3d5-407f-4e14-bec4-e9b49825e76c)

**Comment by grimsi** [comment]
The error pop-up in the frontend is because no connection to the backend could be established.
The backend cant be reached because it cant write to the database.
`Ctrl + C` is indeed the correct way for a graceful shutdown and the logs indicate that the shutdown was graceful.

There are multiple possible reasons for the DB being read-only:

1. Gameyfin does not have write access to the database file (check file system permissions)
2. A second instance of Gameyfin is still running and accessing the database (only one instance can open the database at a time)
3. There is indeed a bug in Gameyfin

For a quick fix I would recommend stopping Gameyfin and deleting the database folder. Gameyfin will automatically create a new database file. If that does not fix the problem, please report back.
Note: This will delete all your libraries, you will have to index them again.

**Comment by crackZ44** [comment]
It indeed was a file permission issue...

Had this on local drives as well as remote folders.

giving the user running gameyfin.jar full access to the folder solved the problem, thank you!
