### ISSUE TITLE
Cant change db and cache path

### ISSUE THREAD

**Issue by crackZ44** [gameyfin/gameyfin#396]
Unable to change the db and cache path

ways i tried
D:\\gameyfin\\.gameyfin\\db
"D:\gameyfin\.gameyfin\db"
D:\gameyfin\.gameyfin\db

gameyfin.properties located in the same directory as gameyfin-1.4.6.jar:

`# Uncomment if you want to specify the Gameyfin database path (default is <game library root>/.gameyfin/db)
gameyfin.db="D:\gameyfin\.gameyfin\db"`

`# Uncomment if you want to specify the Gameyfin cache path (default is <game library root>/.gameyfin/cache)
gameyfin.cache="D:\gameyfin\.gameyfin\cache"`

Installation method: bare metal
Java JDK 22.0.2
Gameyfin version v1.4.6

**Comment by grimsi** [comment]
Can you try the following:
`gameyfin.db="D:\\gameyfin\\.gameyfin\\db"`
`gameyfin.cache="D:\\gameyfin\\.gameyfin\\cache"`
Since `\` is usually used to escape other characters (e.g. `\n` for newline) you have to escape the backslash itself.
This is true for almost all programming languages and documented here: https://docs.oracle.com/javase/tutorial/java/data/characters.html

**Comment by crackZ44** [comment]
copied your path but sadly got the same result.
Still creating cache and db files in game library path


Unable to change path on different Windows 10 Machines.

**Comment by grimsi** [comment]
I just debugged this on my machine and then I remembered that I changed to config variable a while back. It's now `gameyfin.folders.data`. My bad - I'm sorry, since I am fully focused on Gameyfin v2 I'm out of touch with the current version.

This should achieve what you want (be aware that the folder is hidden):
`gameyfin.folders.data=D:/gameyfin`

See https://github.com/gameyfin/gameyfin/issues/153#issuecomment-1757471367
