### ISSUE TITLE
Download progress not shown in browser

### ISSUE THREAD

**Issue by petraexe** [gameyfin/gameyfin#407]
**Describe the bug**
Download progress not shown in browser

**To Reproduce**
1. Download a game
2. Download progress not shown

**Expected behavior**
The game's download size shown in the download progress

**Screenshots**
Arc: 
![CleanShot 2024-09-28 at 17 25 06](https://github.com/user-attachments/assets/f597183b-d9a7-40ae-9a51-df526ad17270)
Firefox:
![CleanShot 2024-09-28 at 17 26 40](https://github.com/user-attachments/assets/7ab3160e-e62a-471e-af9f-892fc4d13c5c)
Safari:
![CleanShot 2024-09-28 at 17 27 56](https://github.com/user-attachments/assets/e602beaa-452a-4a92-9c4a-7dfb2d1f6a04)

**General info (please complete the following information):**
 - Installation method: Docker in Unraid
 - Browser (if bug is in the Web UI) [e.g. chrome, safari]: All browsers tested
 - Gameyfin version [e.g. v1.3.1]: 1.4.6

**Comment by grimsi** [comment]
This is not a bug, but expected behavior. Since browsers do not allow the download of a folder full of files, they are being packed into a ZIP file at runtime.
Since the size of the ZIP file can't be known before Gameyfin doesn't send the content size to the browser (which would allow the browser to show a progress bar).
However you can estimate the duration left by checking the game size on the detail page.
